frontend/src/pages/JobsPage/JobsPage.jsx

If you refresh the page that has "page=N" (where N is some number), then Batchiepatchie will load it as a string.
When you press next page it'll end up doing stuff like "page + 1" which will do thing like "page=3" turn into "page=31" instead of "page=4".
This commit makes it so that the page is parsed as integer when loaded from query parameters.

Fix issue #4 (page is sometimes incorrectly read in as a string)

---

frontend/Dockerfile
migrations/00002_jobs_full_text_search.sql
migrations/00018_job_status_events.sql

This pull request fixes the following issues, which fixes "docker-compose up" to work on a clean install (wasn't before):
* Fixing node docker image
* Fixing db migration scripts

Fixing setup scripts

---

frontend/src/pages/JobPage/JobPage.jsx

In the job page add a direct link to the logs in CloudWatch

Add link to CloudWatch logs

---

docker-compose.yml

The side effect is that this also makes documentation not say lies about how we pass these environment variables to `docker-compose`.
Addresses issue #31

Teach docker-compose.yml to pass AWS credentials from environment.

---

frontend/src/components/Search/Search.jsx
frontend/src/pages/JobsPage/JobsPage.jsx
frontend/src/stores/job.js

This fixes search debouncing, which may inadvertently be a big performance issue with batchiepatchie (backend is trying to answer too many short queries at once... when it shouldn't need to).

Add temp var for search param to effectively debounce search

---

jobs/postgres_store.go
migrations/00022_reduced_trigram_index.sql

**Goal**: Improve search performance by reducing index size.
AdRoll's implemention of this table over 60 million rows. At that scale, very wordy columns like "command_line" take up a lot of space in the index (it's approx. 35% of the table).
This removes the ability to search by `command_line` (large) or by `job_definition` (usually an opaque field users wouldn't be searching for).

Reduced trgm index on jobs table, exclude command_line / job_definition

---

batchiepatchie.go
config/config.go
logentries.go

A dependency has updated that changed how logentries logger is
initialized. You now need to provide a hostname when you instantiate
this logger.
This commit knows the default logentries host, and lets you override it
in configuration file if needed for whatever reason.
The new config item is called `logentries_host`.

Fix compilation error by making logentries host configurable.

---

batchiepatchie.go
config/config.go
jobs/postgres_store.go

I added a config option called `database_root_cert` which should either (1) be left blank, defaulting to current behavior or (2) be the path to an SSL root certificate file. This allows you to utilize something like RDS IAM Authentication for the connection, by setting it to a value such as `/opt/rds-ca-2019-root.pem`.

adding config option for database_root_certificate

---

Dockerfile

The "go get" step in Dockerfile doesn't outpujt anything for several minutes. 
In this PR we make it verbose so we can see its progress.

Make "go get" display its progress

---

migrations/00022_reduced_trigram_index.sql

This PR contains a fix for the error below. The fix is from https://bytemeta.vip/repo/pressly/goose/issues/292	
```
postgres_1    | ERROR:  DROP INDEX CONCURRENTLY cannot run inside a transaction block
postgres_1    | STATEMENT:  -- +goose Up
postgres_1    | 	-- SQL in this section is executed when the migration is applied.
postgres_1    | 	DROP INDEX CONCURRENTLY trgm_idx_jobs;
postgres_1    |
migrations_1  | 2022/07/25 22:13:01 goose run: failed to run SQL migration "00022_reduced_trigram_index.sql": failed to execute SQL query "DROP INDEX CONCURRENTLY trgm_idx_jobs;\n": pq: DROP INDEX CONCURRENTLY cannot run inside a transaction block
batchiepatchie_migrations_1 exited with code 1
```

Fix for database migration error

---

frontend/src/components/Search/Search.scss
frontend/src/components/SectionLoader/SectionLoader.jsx
frontend/src/components/SectionLoader/SectionLoader.scss

This PR adds a spinner back to BatchiePatchie. It seems to have had a spinner before (.ar-spinner) which got lost, probably when the repo moved from being a private repo to a public repo.

Add back spinner

---

frontend/src/pages/JobPage/JobPage.jsx

If info we need is available, add button in job detail page that opens the job details in AWS Batch

add a  Link to batch job info

---

frontend/package.json
frontend/src/components/Search/Search.jsx
frontend/src/components/Search/Search.scss

This adds a tooltip explaining how search works. This is for the new search implementation in https://github.com/AdRoll/batchiepatchie/pull/68/

Add tooltip explaining how search works

---

jobs/jobs.go
jobs/postgres_store.go
migrations/00023_add_array_properties_column.sql
syncer/batchsync.go

AWS returns counts of child array jobs like this:
```
"arrayProperties": {
"statusSummary": {
"STARTING": 0,
"FAILED": 0,
"RUNNING": 1,
"SUCCEEDED": 99,
"RUNNABLE": 0,
"SUBMITTED": 0,
"PENDING": 0
},
"size": 100
},
```
This PR puts this JSON in the jobs table in a JSONB column names array_properties.
We will use this data in an upcoming PR for reporting the statuses of child array jobs.
Note to @jcshott: This PR is easiest reviewed with [whitespace hidden](https://github.com/AdRoll/batchiepatchie/pull/75/files?diff=unified&w=1).

Store array job info in the database

---

jobs/postgres_store.go

This PR adds array job info to the APIs for use by the UI to report stuff about array jobs.
```
"array_properties": {
"size": 100,
"status_summary": {
"starting": 0,
"failed": 0,
"running": 0,
"succeeded": 100,
"runnable": 0,
"submitted": 0,
"pending": 0
}
}
```
This PR depends on https://github.com/AdRoll/batchiepatchie/pull/75

Output array job info

---

frontend/src/pages/JobPage/JobPage.jsx

If a job has no task_arn (like array jobs), extract the region from the desc, so that the Show in AWS Batch button will show up.
job.desc looks like this:
```
arn:aws:batch:us-west-2:11111111111:job-definition/foo-bar-baz:3
```

Try harder to get jobRegion

---

frontend/package.json
frontend/src/components/RowRenderer/RowRenderer.jsx
frontend/src/pages/JobsPage/JobsPage.jsx
frontend/yarn.lock

Update react-data-grid to version v5x (which appears to fix no horizontal scrolling)
there are deprecation warnings that show up and this solves it: https://github.com/adazzle/react-data-grid/issues/1403#issuecomment-499631101
I didn't want to upgrade all the way to v7x (which fixed the warnings) as it doesn't seem stable and could open a pandora's box of problems. one version upgrade seems to be ok.

Fix horizontal scrolling

---

frontend/src/components/Terminal/Terminal.jsx
frontend/src/pages/JobPage/JobPage.jsx
frontend/src/pages/JobPage/JobPage.scss

Add a checkbox for auto-scrolling log output to the bottom when there are new logs.

Add option to auto-scroll log to the bottom

---

frontend/src/components/QueueSelector/QueueSelector.jsx
frontend/src/pages/StatsPage/StatsPage.jsx

use native sort() method since it's all just list of strings so nothing fancy needed.
**Before === anarchy** 🙀 
**After === order** 😌

Sort queues in QueueSelector & fix sorting on stats page table

---

docker_run.sh

Add the -buildvcs=false option. Hoping this will get us past the following error when we try to deploy the service to ECS:
```
2022-07-27T23:02:14.408126585Z + sleep 5
2022-07-27T23:02:19.409570176Z + go build
2022-07-27T23:02:19.573653063Z error obtaining VCS status: exit status 128
2022-07-27T23:02:19.573685073Z 	Use -buildvcs=false to disable VCS stamping.
```
More info: https://github.com/microsoft/CBL-Mariner/issues/3273

Use -buildvcs=false option

---

frontend/src/containers/LayoutContainer/LayoutContainer.jsx

- fix bug where if the index/base path is not `/` the search bar doesn't show
- uses same check for path that the menu component uses: https://github.com/AdRoll/batchiepatchie/blob/master/frontend/src/components/Menu/Menu.jsx#L10
we use `/batchiepatchie/` as basepath so the original check for pathname of index page wasn't correct in non-local env (where it's just `/`):
Production (not showing search):
v. local:

Use basepath to determine if we are on index (jobs) page for search

---

frontend/src/index.scss

- the "select" column (checkboxes) are frozen by default but only the header row actually freezes.
- this causes the alignment to get off and looks weird when scrolling horizontally
- override the transform property of the frozen columns so they aren't frozen
I saw a few issues around the scrolling and the select column stickiness - [this was the simplest](https://github.com/adazzle/react-data-grid/issues/1386#issuecomment-510532495) (if not a bit hacky) answer outside of upgrading to v7+ which I'm not prepared to do here.
Seems relatively low-risk as we aren't using frozen columns anywhere else.
Current:
Fixed:

Override CSS property of the frozen header

---

frontend/Dockerfile

Fix a couple of build errors I saw while running BatchiePatchie locally today.

Fix a couple of build errors

---

Dockerfile

docker-compose up was giving this error:
```
#11 10.56 # github.com/go-delve/delve/pkg/proc/gdbserial
#11 10.56 /go/pkg/mod/github.com/go-delve/delve@v1.23.0/pkg/proc/gdbserial/rr.go:247:35: undefined: strings.CutPrefix
#11 10.56 /go/pkg/mod/github.com/go-delve/delve@v1.23.0/pkg/proc/gdbserial/rr.go:248:33: undefined: strings.CutPrefix
#11 10.56 note: module requires Go 1.21
```
Upgrade Go from 1.18 to 1.21

UDP-3844: Upgrade Go to 1.21

---

syncer/batchsync.go

This error was occurring on startup:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa99cf5]
goroutine 114 [running]:
github.com/AdRoll/batchiepatchie/syncer.syncJobsStatus({0x7f72d07369d8, 0xc0004cc6d8}, {0xd91af9, 0x6}, {0xc000501000, 0x40, 0xc000a3fbd8?}, 0x47a99b?, {0x10313c0, 0xc0003b4378})
/go/src/github.com/AdRoll/batchiepatchie/syncer/batchsync.go:125 +0xed5
github.com/AdRoll/batchiepatchie/syncer.syncJobs({0x7f72d07369d8, 0xc0004cc6d8}, {0xc000501000, 0x40, 0x40})
/go/src/github.com/AdRoll/batchiepatchie/syncer/batchsync.go:267 +0x2bd
github.com/AdRoll/batchiepatchie/syncer.RunSynchronizer({0x1032770?, 0xc0004cc6d8}, {0xc000501000, 0x40, 0x40}) …
```

UDP-3844: Fix nil pointer dereference

---

frontend/src/components/Search/Search.jsx
frontend/src/pages/JobsPage/JobsPage.jsx
frontend/src/stores/job.js
handlers/handlers.go
jobs/jobs.go
jobs/postgres_store.go

Note: This PR has been split into smaller commits for easier review.
This PR dramatically speeds up batchiepatchie by adding a date filter. If you choose 1 day, queries that used to time out (because they were hardcoded to look back 30 days) will load in under 1 second.

Speed up batchiepatchie by adding a date-range filter that defaults to 1 day
